receivers:
  fluentforward:
    endpoint: 0.0.0.0:24224
  otlp:
    protocols:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      namespace: MY_NAMESPACE
      project: MY_PROJECT
  logging:
  otlp:
    endpoint: tempo:55680
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    sending_queue:
      # Enabled indicates whether to not enqueue batches before sending to the consumerSender.
      enabled: false
      # NumConsumers is the number of consumers from the queue.
      num_consumers: 100
      # QueueSize is the maximum number of batches allowed in queue at a given time.
      queue_size: 10000
    tenant_id: yyy
    # Labels defines how labels should be applied to log streams sent to Loki.
    labels:
      # ResourceAttributes are the resource attributes that are allowed to be added as labels on a log stream.
      resource:
        project: ""
        namespace: ""
        container_name: ""
        source: ""
        "service.version": ""
        "service.namespace": ""
        "service.name": ""
      # Attributes are the log record attributes that are allowed to be added as labels on a log stream.
      attributes:
        level: ""
# flog required attibutes for container
#        container_name: ""
#        source: ""
processors:
  resource:
    attributes:
      - key: host.name
        value: zone-1
        action: upsert
      - key: host.name2
        from_attribute: host.name
        action: insert
      - key: host.name3
        from_attribute: host.name
        action: insert
  batch:
    send_batch_size: 50
    timeout: 5s
  # Enabling the memory_limiter is strongly recommended for every pipeline.
  # Configuration is based on the amount of memory allocated to the collector.
  # The configuration below assumes 2GB of memory. In general, the ballast
  # should be set to 1/3 of the collector's memory, the limit should be 90% of
  # the collector's memory up to 2GB, and the spike should be 25% of the
  # collector's memory up to 2GB. In addition, the "--mem-ballast-size-mib" CLI
  # flag must be set to the same value as the "ballast_size_mib". For more
  # information, see
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md
  memory_limiter:
    #ballast_size_mib: 683
    check_interval: 2s
    limit_mib: 1800
    spike_limit_mib: 500

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [ pprof, zpages, health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, otlp ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch, resource ]
      exporters: [ logging, prometheus ]
    logs:
      receivers: [ fluentforward, otlp ]
      processors: [ memory_limiter, batch ]
      exporters: [ logging, loki ]
